apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient
  template:
    metadata:
      labels:
        app: patient
    spec:
      containers:
        - name: patient
          image: asia-south1-docker.pkg.dev/sapient-origin-370513/devops-hackathon/patient:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always

      
    